---
- hosts: webserver
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
    become: yes

  - name: Ensure Apache is running
    service:
      name: apache2
      state: started
    become: yes
